kind: Pod
apiVersion: v1
metadata:
  name: annotations
  labels: 
    name: sathish
    place: hyd
  annotations:
    kubernetes.io/created-by: 'sathish reddy'
    jenkins.build.url: 'https://jenkins.sathishreddy.online/expense/job/backend/54'
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      # soft limit
      requests:
        cpu: "100m"
        memory: "128Mi"
      # limits should be atleast or more than requests i.e hard limit
      limits:
        cpu: "100m"
        memory: "128Mi"
