apiVersion: v1
kind: Pod
metadata:
  name: pod-config
  labels:
    name: config
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
    - configMapRef:
        name: sathish
    # env:
    # - name : first-name
    #   valueFrom: 
    #     configMapKeyRef:
    #       name: sathish  
    #       key: first-name
    # - name : last-name
    #   valueFrom:
    #     configMapKeyRef:
    #       name: sathish
    #       key: last-name
