apiVersion: v1
kind: Pod
metadata:
  name: pod-config
  labels:
    name: config
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    environment:
    - name : name
      valueFrom: 
        configMapKeyRef:
          name: sathish  
          key: name
