kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  # these labels are deployment related labels
  labels:
    app: nginx
    purpose: deployment
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: web
      project: test-project
  # pod definition
  template:
    metadata:
      labels:
        app: nginx
        tier: web
        project: test-project
        extra-key: extra-value
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          # soft limit
          requests:
          cpu: "100m"
          memory: "128Mi"
          # limits should be atleast or more than requests i.e hard limit
          limits:
            cpu: "100m"
            memory: "128Mi"
      
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
    tier: web
    project: test-project
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port